//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiemTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBill
    {
        public int IdCTBill { get; set; }
        public Nullable<int> IdBill { get; set; }
        public int IdTU { get; set; }
        public string Size { get; set; }
        public int SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual ThucUong ThucUong { get; set; }
    }
}
