//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiemTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoNguyenLieu
    {
        public int IdNL { get; set; }
        public string LoHang { get; set; }
        public Nullable<int> TenNL { get; set; }
        public Nullable<int> IdNhaCC { get; set; }
        public string DVT { get; set; }
        public Nullable<int> TonKho { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
