//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiemTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucUong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThucUong()
        {
            this.CongThuc = new HashSet<CongThuc>();
            this.ChiTietBill = new HashSet<ChiTietBill>();
        }
    
        public int IdTU { get; set; }
        public string TenTU { get; set; }
        public Nullable<int> IdLoai { get; set; }
        public Nullable<int> IdSize { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<System.DateTime> Date_update { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongThuc> CongThuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBill> ChiTietBill { get; set; }
        public virtual LoaiThucUong LoaiThucUong { get; set; }
        public virtual Size Size { get; set; }
    }
}
